<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesBlogEntryProxy extends \Entities\Blog\Entry implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getUrl()
    {
        $this->_load();
        return parent::getUrl();
    }

    public function getArchiveUrl()
    {
        $this->_load();
        return parent::getArchiveUrl();
    }

    public function getPermalinkUrl()
    {
        $this->_load();
        return parent::getPermalinkUrl();
    }

    public function getBreadcrumbs($url = 'UNINITIALIZED', $result = array (
))
    {
        $this->_load();
        return parent::getBreadcrumbs($url, $result);
    }

    public function updated()
    {
        $this->_load();
        return parent::updated();
    }

    public function __get($key)
    {
        $this->_load();
        return parent::__get($key);
    }

    public function __set($key, $val)
    {
        $this->_load();
        return parent::__set($key, $val);
    }

    public function __call($name, $args)
    {
        $this->_load();
        return parent::__call($name, $args);
    }

    public function setData($data)
    {
        $this->_load();
        return parent::setData($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'permalink', 'title', 'pub_date', 'content', 'comments', 'created_at', 'updated_at');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}